import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;
import javax.swing.JButton;
import java.awt.Component;
import javax.swing.Box;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JSeparator;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rarys
 */
public class CadastroLivro extends javax.swing.JFrame {

    /**
     * Creates new form cadastroLivroo
     */
	DefaultComboBoxModel modeloAutor;
	
    public CadastroLivro() {
        initComponents();
        
        modeloAutor =(DefaultComboBoxModel) comboBox.getModel();
        atualizarAutores("");
    }
    
    public void atualizarAutores(String texto) {
    	ConexaoTabelas bd = new ConexaoTabelas();
    	modeloAutor.removeAllElements();
    	
    	for(Autor a:bd.consultarAutor(texto)) {
    		modeloAutor.addElement(a);
    	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIsbn = new javax.swing.JLabel();
        lblIsbn.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblIsbn.setBounds(6, 16, 106, 14);
        txtIsbn = new javax.swing.JTextField();
        txtIsbn.setBounds(122, 13, 344, 20);
        lblGenero = new javax.swing.JLabel();
        lblGenero.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblGenero.setBounds(6, 70, 106, 25);
        lblGenero.setHorizontalAlignment(SwingConstants.CENTER);
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ConexaoTabelas bd = new ConexaoTabelas();
        		
        		String isbn = txtIsbn.getText().trim();
        		String titulo = txtTitulo.getText().trim();
        		String genero = txtGenero.getText().trim();
        		String autor = ((Autor) modeloAutor.getSelectedItem()).toString();
        		
        		if(isbn.isEmpty()||titulo.isEmpty()||modeloAutor.getSelectedItem()==null) {
        			JOptionPane.showMessageDialog(null,"Preencha os campos (o campo 'G�nero' � opcional)","Preencha os campos!",JOptionPane.INFORMATION_MESSAGE);
        			return;
        		}
        		
        		bd.insertLivro(isbn, titulo, autor, genero);
        		
        		txtIsbn.setText("");
        		txtTitulo.setText("");
        		txtGenero.setText("");
        		txtAutor.setText("");
        	}
        });
        jButton1.setBounds(383, 255, 83, 23);
        jButton2 = new javax.swing.JButton();
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		txtIsbn.setText("");
        		txtTitulo.setText("");
        		txtGenero.setText("");
        		txtAutor.setText("");
        		
        	}
        });
        jButton2.setBounds(315, 255, 65, 23);
        txtGenero = new javax.swing.JTextField();
        txtGenero.setBounds(122, 78, 344, 20);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CADASTRO DE LIVRO");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblIsbn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIsbn.setText("ISBN:");

        lblGenero.setText("Gênero");

        jButton1.setText("Cadastrar");

        jButton2.setText("Limpar");
        
        JLabel lblAutor = new JLabel("Autor");
        lblAutor.setBounds(42, 166, 32, 14);
        lblAutor.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 11));
        
        txtAutor = new JTextField();
        txtAutor.setBounds(84, 162, 168, 20);
        txtAutor.setToolTipText("Pesquisar pelo autor");
        txtAutor.setColumns(10);
        
        JButton btnProcurar = new JButton("Procurar");
        btnProcurar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ConexaoTabelas bd = new ConexaoTabelas();
        		String texto = txtAutor.getText().trim();
        		
        		modeloAutor.removeAllElements();
        		
        		for(Autor a:bd.consultarAutor(texto)) {
        			modeloAutor.addElement(a);
        		}
        		
        	}
        });
        btnProcurar.setBounds(272, 162, 75, 23);
        btnProcurar.setHorizontalAlignment(SwingConstants.LEFT);
        
        comboBox = new JComboBox<Livro>();
        comboBox.setBounds(371, 162, 95, 22);
        
        lblTitulo = new JLabel("T\u00EDtulo:");
        lblTitulo.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitulo.setBounds(6, 41, 106, 18);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        				.addComponent(jPanel2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 289, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2.setLayout(null);
        jPanel2.add(lblAutor);
        jPanel2.add(lblIsbn);
        jPanel2.add(lblGenero);
        jPanel2.add(txtIsbn);
        jPanel2.add(jButton2);
        jPanel2.add(jButton1);
        jPanel2.add(txtGenero);
        jPanel2.add(comboBox);
        jPanel2.add(txtAutor);
        jPanel2.add(btnProcurar);
        jPanel2.add(lblTitulo);
        
        txtTitulo = new JTextField();
        txtTitulo.setBounds(122, 47, 344, 20);
        jPanel2.add(txtTitulo);
        txtTitulo.setColumns(10);
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtGenero;
    private JTextField txtAutor;
    private JComboBox comboBox;
    private JLabel lblTitulo;
    private JTextField txtTitulo;
}
