/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JPopupMenu;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
/**
 *
 * @author rarys
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
	DefaultTableModel modeloLivro;
	DefaultTableModel modeloAutor;
	DefaultTableModel modeloEmprestimo;
	
    public Interface() {
        initComponents();
        modeloLivro =(DefaultTableModel) jTable1.getModel();
        modeloAutor = (DefaultTableModel) jTable2.getModel();
        modeloEmprestimo = (DefaultTableModel) jTable3.getModel();
        
        this.atualizarTabelaLivro();
        this.atualizarTabelaEmprestimo();
        this.atualizarTabelaAutor();
    }
    
    private void atualizarTabelaLivro() {
    	modeloLivro.setNumRows(0);
    	ConexaoTabelas bd = new ConexaoTabelas();
    	
    	for(Livro l:bd.consultarLivro("",0)) {
    		modeloLivro.addRow(new Object[] {l.getIsbn(),l.getTitulo(),l.getAutor(),l.getGenero(),l.getEstado()});
    	}
    }
    
    private void atualizarTabelaAutor() {
    	modeloAutor.setNumRows(0);
    	ConexaoTabelas bd = new ConexaoTabelas();
    	
    	for(Autor a:bd.consultarAutor("")) {
    		modeloAutor.addRow(new Object[] {a.getNome(),a.getSexo()});
    	}
    }
    
    private void atualizarTabelaEmprestimo() {
    	modeloEmprestimo.setNumRows(0);
    	ConexaoTabelas bd = new ConexaoTabelas();
    	
    	for(Emprestimo e:bd.consultarEmprestimo("",0)) {
    		modeloEmprestimo.addRow(new Object[] {e.getId(),e.getLeitor(),e.getLivro(),e.getTelefone(),e.getEndereco(),e.getEmprestimo(),e.getDevolucao()});
    	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		// ------------------------------------CONSULTAR TABELA LIVRO -----------------------------
        		modeloLivro.setNumRows(0);
        		ConexaoTabelas bd = new ConexaoTabelas();
        		String texto = jTextField1.getText().trim();
        		int opcao = jComboBox1.getSelectedIndex();
        		
        		for(Livro l:bd.consultarLivro(texto,opcao)) {
        			modeloLivro.addRow(new Object[] {l.getIsbn(),l.getTitulo(),l.getAutor(),l.getGenero(),l.getEstado()});
        		}
        	
        	}
        });
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		// -------------------------------PROCURAR AUTOR----------------------------------
        		modeloAutor.setNumRows(0);
        		ConexaoTabelas bd = new ConexaoTabelas();
        		String texto = jTextField2.getText().trim();
        		int opcao = jComboBox2.getSelectedIndex();
        		
        		for(Autor a:bd.consultarAutor(texto)) {
        			modeloAutor.addRow(new Object[] {a.getNome(),a.getSexo()});
        		}
        	}
        });
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton5.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		//--------------PESQUISAR REGISTRO DE EMPRÉSTIMO ------------------------------
        		modeloEmprestimo.setNumRows(0);
        		ConexaoTabelas bd = new ConexaoTabelas();
        		String texto = jTextField3.getText().trim();
        		int opcao = jComboBox2.getSelectedIndex();
        		
        		for(Emprestimo emp:bd.consultarEmprestimo(texto, opcao)) {
        			modeloEmprestimo.addRow(new Object[] {emp.getId(),emp.getLeitor(),emp.getLivro(),emp.getTelefone(),emp.getEndereco(),emp.getEmprestimo(),emp.getDevolucao()});
        		}
        		
        	}
        });
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Biblioteca");

        jLabel1.setText("Consulta:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Título", "Autor", "Gênero" }));

        jButton1.setText("Pesquisar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ISBN","Título", "Autor", "Gênero","Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false,false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        
        popupMenu = new JPopupMenu();
        addPopup(jTable1, popupMenu);
        
        mntmRemover = new JMenuItem("Remover");
        mntmRemover.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		// DELETAR LINHA DA TABELA
        		ConexaoTabelas bd = new ConexaoTabelas();
        		String isbn = modeloLivro.getValueAt(jTable1.getSelectedRow(),0).toString();
        		
        		if(bd.deleteLivro(isbn)) {
        			modeloLivro.removeRow(jTable1.getSelectedRow());
        		}
        	}
        });
        popupMenu.add(mntmRemover);
        
        mntmModificar = new JMenuItem("Modificar");
        mntmModificar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String isbn = modeloLivro.getValueAt(jTable1.getSelectedRow(),0).toString();
        		String titulo= modeloLivro.getValueAt(jTable1.getSelectedRow(),1).toString();
        		String autor = modeloLivro.getValueAt(jTable1.getSelectedRow(),2).toString();
        		String genero = modeloLivro.getValueAt(jTable1.getSelectedRow(),3).toString();
        		
        		new AtualizacaoLivro(isbn,titulo,autor,genero).setVisible(true);
        	}
        });
        popupMenu.add(mntmModificar);

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Livro", jPanel1);

        jLabel2.setText("Consulta:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome"}));

        jButton3.setText("Pesquisar");

        jButton4.setText("Cadastrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        
        popupMenu_1 = new JPopupMenu();
        addPopup(jTable2, popupMenu_1);
        
        mntmRemover_1 = new JMenuItem("Remover");
        mntmRemover_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		// REMOVER AUTOR
        		
        		ConexaoTabelas bd = new ConexaoTabelas();
        		String nome = modeloAutor.getValueAt(jTable2.getSelectedRow(),0).toString();
        		
        		if(bd.deleteAutor(nome)) {
        			modeloAutor.removeRow(jTable2.getSelectedRow());
        		}
        		
        	}
        });
        popupMenu_1.add(mntmRemover_1);
        
        mntmModificar_1 = new JMenuItem("Modificar");
        mntmModificar_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String nome = (modeloAutor.getValueAt(jTable2.getSelectedRow(),0)).toString();
        		String sexo = (modeloAutor.getValueAt(jTable2.getSelectedRow(),1)).toString();
        		
        		new AtualizacaoAutor(nome,sexo).setVisible(true);
        	}
        });
        popupMenu_1.add(mntmModificar_1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Autor", jPanel2);

        jLabel3.setText("Consulta:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leitor", "Livro" }));

        jButton5.setText("Pesquisar");

        jButton6.setText("Emprestar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID","Leitor", "Livro", "Telefone","Endereço","Empréstimo","Devolução"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false,false,false,false,false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);
        
        popupMenu_2 = new JPopupMenu();
        addPopup(jTable3, popupMenu_2);
        
        mntmRemover_2 = new JMenuItem("Remover");
        mntmRemover_2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		// REMOVER EMPRÉSTIMO
        		ConexaoTabelas bd = new ConexaoTabelas();
        		int id = Integer.parseInt(modeloEmprestimo.getValueAt(jTable3.getSelectedRow(),0).toString());
        		String isbn = (modeloEmprestimo.getValueAt(jTable3.getSelectedRow(),2)).toString();

        		if(bd.deleteEmprestimo(id)) {
        			modeloEmprestimo.removeRow(jTable3.getSelectedRow());
                    		bd.updateEstado(isbn,"Disponível");
        		}
        		
        	}
        });
        
        mntmExecutarDevoluo = new JMenuItem("Executar Devolu\u00E7\u00E3o");
        mntmExecutarDevoluo.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ConexaoTabelas bd = new ConexaoTabelas();
        		int id = Integer.parseInt(modeloEmprestimo.getValueAt(jTable3.getSelectedRow(),0).toString());
        		String isbn = (modeloEmprestimo.getValueAt(jTable3.getSelectedRow(),2)).toString();

        		if(modeloEmprestimo.getValueAt(jTable3.getSelectedRow(),6)!=null) {
        			JOptionPane.showMessageDialog(null,"Este livro ja foi devolvido!","ERRO",JOptionPane.ERROR_MESSAGE);
        			return;
        		}
        		bd.executarDevolucao(id);
        		bd.updateEstado(isbn,"Disponível");

        	}
        });
        popupMenu_2.add(mntmExecutarDevoluo);
        popupMenu_2.add(mntmRemover_2);
        
        mntmModificar_2 = new JMenuItem("Modificar");
        mntmModificar_2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		ConexaoTabelas bd = new ConexaoTabelas();
        		
        		int id = Integer.parseInt(modeloEmprestimo.getValueAt(jTable3.getSelectedRow(),0).toString());
        		String leitor = modeloEmprestimo.getValueAt(jTable3.getSelectedRow(),1).toString();
        		Livro livro = bd.consultarLivroEspecifico(modeloEmprestimo.getValueAt(jTable3.getSelectedRow(),2).toString());
        		String telefone = modeloEmprestimo.getValueAt(jTable3.getSelectedRow(),3).toString();
        		String endereco = modeloEmprestimo.getValueAt(jTable3.getSelectedRow(),4).toString();
        		
        		new AtualizacaoEmprestimo(id,leitor,endereco,telefone,livro).setVisible(true);
        		
        	}
        });
        popupMenu_2.add(mntmModificar_2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Empréstimo", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new CadastroLivro().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new CadastroAutor().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new RegistroEmprestimo().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private JPopupMenu popupMenu;
    private JMenuItem mntmRemover;
    private JPopupMenu popupMenu_1;
    private JMenuItem mntmRemover_1;
    private JPopupMenu popupMenu_2;
    private JMenuItem mntmRemover_2;
    private JMenuItem mntmExecutarDevoluo;
    private JMenuItem mntmModificar;
    private JMenuItem mntmModificar_1;
    private JMenuItem mntmModificar_2;
    // End of variables declaration//GEN-END:variables
	private static void addPopup(Component component, final JPopupMenu popup) {
		component.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			public void mouseReleased(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			private void showMenu(MouseEvent e) {
				popup.show(e.getComponent(), e.getX(), e.getY());
			}
		});
	}
}
